plugins {
    id("multiloader-loader")
    id("fabric-loom")
}

repositories {
    maven {
        name = "Modrinth"
        url = uri("https://api.modrinth.com/maven")
    }
    maven {
        name = "JitPack"
        url = uri("https://jitpack.io")
    }
}

dependencies {
    minecraft("com.mojang:minecraft:${rootProject.property("minecraft_version").toString()}")
    mappings (loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${rootProject.property("parchment_minecraft").toString()}:${rootProject.property("parchment_version").toString()}@zip")
    })
    modImplementation("net.fabricmc:fabric-loader:${rootProject.property("fabric_loader_version").toString()}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${rootProject.property("fabric_version").toString()}")

    // Spark
    compileOnly("maven.modrinth:spark:${libs.versions.spark}-fabric")

    for (dep in libs.bundles.jijs.get()) {
        implementation(include(dep))
    }
//    // JSON
//    implementation (include(libs.json.get()))
//    // Mclogs Java
//    implementation (include(libs.mclogs.get()))
//    // Jankson
//    implementation (include(libs.jankson.get()))
//    // BlossomBridge
//    implementation (include(libs.bbapi.get()))
}

loom {
    var aw = project(':common').file("src/main/resources/${rootProject.property("mod_id").toString()}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${rootProject.property("mod_id").toString()}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}