plugins {
    id("multiloader-loader")
    id("fabric-loom")
}

repositories {
    maven {
        name = "Modrinth"
        url = uri("https://api.modrinth.com/maven")
    }
    maven {
        name = "JitPack"
        url = uri("https://jitpack.io")
    }
}

dependencies {
    minecraft("com.mojang:minecraft:${minecraft_version}")
    mappings (loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.parchment_minecraft}:${project.parchment_version}@zip")
    })
    modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}")

    // Spark
    compileOnly("maven.modrinth:spark:${project.spark_version}-fabric")

    for (dep in libs.bundles.jijs.get()) {
        implementation(include(dep))
    }
//    // JSON
//    implementation (include(libs.json.get()))
//    // Mclogs Java
//    implementation (include(libs.mclogs.get()))
//    // Jankson
//    implementation (include(libs.jankson.get()))
//    // BlossomBridge
//    implementation (include(libs.bbapi.get()))
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}