plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
}

repositories {
    mavenCentral()
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
    maven {
        name = 'JitPack'
        url = 'https://jitpack.io'
    }
    maven {
        name = "KordEx (Snapshots, R2)"
        url = uri("https://snapshots-repo.kordex.dev")
    }
    maven {
        name = "KordEx (Releases, R2)"
        url = uri("https://releases-repo.kordex.dev")
    }
    maven {
        name = "KordEx (Snapshots + Mirror, Reposilite)"
        url = uri("https://repo.kordex.dev/snapshots")
    }
    maven {
        name = "KordEx (Mirror, R2)"
        url = uri("https://mirror-repo.kordex.dev")
    }
    flatDir {
        dirs("${rootProject.projectDir}/.gradle/localLibs")
    }
    maven {
        name = "QuiltMC (Snapshots)"
        url = uri("https://maven.quiltmc.org/repository/snapshot/")
        metadataSources {
            gradleMetadata()
            // Ignore gradle telling us to use the .module file, stick with the POM
            ignoreGradleMetadataRedirection()
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // Spark
    compileOnly "maven.modrinth:spark:${project.spark_version}-fabric"
    // JSON
    implementation include("org.json:json:${project.json_version}")
    // Mclogs Java
    implementation include("gs.mclo:api:${project.mclogs_version}")
    // BlossomBridge
    api include("com.github.Tywrap-Studios:BlossomBridge:${project.blossombridge_version}")
    // Krafter
    api include(project(":krafter"))
    api include('io.github.oshai:kotlin-logging-jvm:7.0.3')
    implementation include("dev.kord:kord-core:0.17.0-SNAPSHOT")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}