[versions]
detekt = "1.23.6"
kotlin = "2.1.21"
ksp = "2.1.21-2.0.1"

groovy = "3.0.23"
jansi = "2.4.1"
kx-ser = "1.8.1"
logback = "1.5.18"
logback-groovy = "1.14.5"
logging = "7.0.7"
kordex-gradle = "1.7.1"
kordex = "2.3.2-SNAPSHOT"

cozy-modules = "1.0.1-SNAPSHOT"
json = "20231013"
mclogs = "5.0.2"
jankson = "1.2.3"
bbapi = "master-SNAPSHOT"
spark = "1.10.109"

[libraries]
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kx-ser = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kx-ser" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-groovy = { module = "io.github.virtualdogbert:logback-groovy-config", version.ref = "logback-groovy" }
logging = { module = "io.github.oshai:kotlin-logging", version.ref = "logging" }
cozy-log-parser = { module = "org.quiltmc.community:module-log-parser", version.ref = "cozy-modules" }
cozy-moderation = { module = "org.quiltmc.community:module-moderation", version.ref = "cozy-modules" }
cozy-tags = { module = "org.quiltmc.community:module-tags", version.ref = "cozy-modules" }
cozy-user-cleanup = { module = "org.quiltmc.community:module-user-cleanup", version.ref = "cozy-modules" }
json = { module = "org.json:json", version.ref = "json" }
mclogs = { module = "gs.mclo:api", version.ref = "mclogs" }
jankson = { module = "blue.endless:jankson", version.ref = "jankson" }
bbapi = { module = "com.github.Tywrap-Studios:BlossomBridge", version.ref = "bbapi" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

kordex-docker = { id = "dev.kordex.gradle.docker", version.ref = "kordex-gradle" }
kordex-plugin = { id = "dev.kordex.gradle.kordex", version.ref = "kordex-gradle" }
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
cozy-modules = [
	"cozy-log-parser",
	"cozy-moderation",
	"cozy-tags",
	"cozy-user-cleanup",
]

jijs = [
	"json",
	"mclogs",
	"jankson",
	"bbapi"
]
