plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'JitPack'
        url = 'https://jitpack.io'
    }
    maven {
        name = "Sonatype Snapshots"
        url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots")
    }
    maven {
        name = "KordEx (Snapshots, R2)"
        url = uri("https://snapshots-repo.kordex.dev")
    }
    maven {
        name = "KordEx (Releases, R2)"
        url = uri("https://releases-repo.kordex.dev")
    }
    maven {
        name = "KordEx (Snapshots + Mirror, Reposilite)"
        url = uri("https://repo.kordex.dev/snapshots")
    }
    maven {
        name = "KordEx (Mirror, R2)"
        url = uri("https://mirror-repo.kordex.dev")
    }
    maven {
        name = "Fabric"
        url = uri("https://maven.fabricmc.net")
    }
    maven {
        name = "QuiltMC (Releases)"
        url = uri("https://maven.quiltmc.org/repository/release/")
    }
    maven {
        name = "QuiltMC (Snapshots)"
        url = uri("https://maven.quiltmc.org/repository/snapshot/")
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    // ASM tree
    compileOnly 'org.ow2.asm:asm-tree:9.7.1'
    compileOnly 'org.ow2.asm:asm:9.7'

    // JSON
    implementation("org.json:json:${project.json_version}")
    // Mclogs Java
    implementation("gs.mclo:api:${project.mclogs_version}")
    // BlossomBridge
    api("com.github.Tywrap-Studios:BlossomBridge:${project.blossombridge_version}")
    // Krafter
    api(project(":krafter"))
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

