plugins {
    id("multiloader-loader")
    id("net.neoforged.moddev")
}

repositories {
    maven {
        name = "Modrinth"
        url = uri("https://api.modrinth.com/maven")
    }
    maven {
        name = "JitPack"
        url = uri("https://jitpack.io")
    }
}

dependencies {
    // Spark
    compileOnly("maven.modrinth:spark:${project.spark_version}-neoforge")

    for (dep in libs.bundles.jijs.get()) {
        implementation(dep) {
            exclude group: "org.slf4j", module: "slf4j-api"
            exclude group: "com.google.code.gson", module: "gson"
        }
    }

//    // JSON
//    jarJar (implementation (additionalRuntimeClasspath libs.json.get()))
//    // Mclogs Java
//    jarJar (implementation (additionalRuntimeClasspath libs.mclogs.get())) {
//        exclude(group = "com.google.code.gson",) module = "gson"
//    }
//    // Jankson
//    jarJar (implementation (additionalRuntimeClasspath libs.jankson.get()))
//    // BlossomBridge
//    jarJar (implementation (additionalRuntimeClasspath libs.bbapi.get())) {
//        exclude(group = "org.slf4j",) module = "slf4j-api"
//    }

    // Explicit dependencies with compatible versions
    implementation("com.google.code.gson:gson:2.10.1")
    implementation("org.slf4j:slf4j-api:2.0.9")
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty("neoforge.enabledGameTestNamespaces", mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir "src/generated/resources" }