plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

repositories {
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
    maven {
        name = 'JitPack'
        url = 'https://jitpack.io'
    }
}

dependencies {
    // Spark
    compileOnly "maven.modrinth:spark:${project.spark_version}-neoforge"

    // JSON
    jarJar (implementation (additionalRuntimeClasspath "org.json:json:${project.json_version}"))
    // Mclogs Java
    jarJar (implementation (additionalRuntimeClasspath "gs.mclo:api:${project.mclogs_version}")) {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    // Jankson
    jarJar (implementation (additionalRuntimeClasspath "blue.endless:jankson:${project.jankson_version}"))
    // BlossomBridge
    jarJar (implementation (additionalRuntimeClasspath "com.github.Tywrap-Studios:BlossomBridge:${project.blossombridge_version}")) {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }

    // Explicit dependencies with compatible versions
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.slf4j:slf4j-api:2.0.9'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }