plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

repositories {
    mavenCentral()
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
    maven {
        name = 'JitPack'
        url = 'https://jitpack.io'
    }
    maven {
        name = "KordEx (Snapshots, R2)"
        url = uri("https://snapshots-repo.kordex.dev")
    }
    maven {
        name = "KordEx (Releases, R2)"
        url = uri("https://releases-repo.kordex.dev")
    }
    maven {
        name = "KordEx (Snapshots + Mirror, Reposilite)"
        url = uri("https://repo.kordex.dev/snapshots")
    }
    maven {
        name = "KordEx (Mirror, R2)"
        url = uri("https://mirror-repo.kordex.dev")
    }
    maven {
        name = "Fabric"
        url = uri("https://maven.fabricmc.net")
    }
    maven {
        name = "QuiltMC (Releases)"
        url = uri("https://maven.quiltmc.org/repository/release/")
    }
    maven {
        name = "QuiltMC (Snapshots)"
        url = uri("https://maven.quiltmc.org/repository/snapshot/")
    }
}

dependencies {
    // Spark
    compileOnly "maven.modrinth:spark:${project.spark_version}-neoforge"

    // JSON
    jarJar (implementation (additionalRuntimeClasspath "org.json:json:${project.json_version}"))
    // Mclogs Java
    jarJar (implementation (additionalRuntimeClasspath "gs.mclo:api:${project.mclogs_version}")) {
        exclude group: 'com.google.code.gson', module: 'gson'
    }
    // BlossomBridge
    jarJar (api (additionalRuntimeClasspath "com.github.Tywrap-Studios:BlossomBridge:${project.blossombridge_version}")) {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
    // Krafter
//    jarJar (implementation additionalRuntimeClasspath (project(":krafter"))) {
//        exclude module: 'slf4j-api'
//        exclude module: 'icu4j'
//        exclude module: 'oshi-core'
//        exclude module: 'commons-logging'
//    }
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }